"""
Django settings for tubewhale_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, s# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', '简体中文'),
    ('zh-hant', '繁體中文'),
    ('ja', '日本語'),
    ('ko', '한국어'),
    ('es', 'Espa# ============== CACHES CONFIGURATION ==============
# Use Redis for production-grade caching and channel layers
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
        },
        'KEY_PREFIX': 'tubewhale',
        'TIMEOUT': 300,  # 5 minutes default timeout
    },
    # Fallback to local memory cache if Redis unavailable
    'localmem': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}r', 'Français'),
    ('de', 'Deutsch'),
    ('pt', 'Português'),
    ('ru', 'Русский'),
]

# Translation paths
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Session settings for language preference
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 86400 * 30  # 30 days
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Session and Cookie Security Settings for Admin
SESSION_COOKIE_SECURE = False  # Set to True for HTTPS in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = False  # Don't save on every request

# CSRF Protection Settings
CSRF_COOKIE_SECURE = False  # Set to True for HTTPS in production  
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_AGE = 86400 * 7  # 7 days
CSRF_USE_SESSIONS = False  # Use cookie instead of session for CSRF

# Admin specific settings to prevent logout issues
ADMIN_SESSION_TIMEOUT = 86400 * 7  # 7 days for admin users

# Admin site language forcing
ADMIN_LANGUAGE_COOKIE_NAME = 'admin_language'
ADMIN_LANGUAGE_COOKIE_AGE = 86400 * 365  # 1 year

# Django settings documentation:
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    # Load .env from project root
    dotenv_path = Path(__file__).resolve().parent.parent / '.env'
    if dotenv_path.exists():
        load_dotenv(dotenv_path)
        print(f"✅ Loaded .env from {dotenv_path}")
    else:
        print(f"⚠️  No .env file found at {dotenv_path}")
except ImportError:
    print("⚠️  python-dotenv not installed, skipping .env loading")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 添加项目根目录到Python路径，这样可以import service/, utils/, agents/
sys.path.insert(0, str(BASE_DIR))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0,testserver').split(',')

# Application definition

DJANGO_APPS = [
    'admin_interface',  # 必须在django.contrib.admin之前
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'django_extensions',
    'import_export',
    'guardian',
    'drf_spectacular',
    'django_redis',
    'django_celery_beat',
    'channels',  # 🎯 WebSocket支持
]

LOCAL_APPS = [
    'tubewhale_project',  # 包含管理命令
    'apps.user_app',
    'apps.video_app', 
    'apps.analysis_app',
    'apps.api_app',
    'apps.tubewhale_engine',  
    'apps.templates_app',
    'apps.dashboard_app',  # 添加dashboard_app
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# Custom User Model
AUTH_USER_MODEL = 'user_app.User'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'apps.user_app.middleware.AdminLanguageMiddleware',  # MUST be before LocaleMiddleware!
    'django.middleware.locale.LocaleMiddleware',  # Language support
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tubewhale_project.urls'

# Force English for prompt/template catalog APIs (override via env)
FORCE_EN_PROMPTS = os.environ.get('FORCE_EN_PROMPTS', 'true').lower() == 'true'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'tubewhale_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', str(BASE_DIR / 'tubewhale.db')),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'     # Default language: English
TIME_ZONE = 'UTC'        # Default timezone: UTC

USE_I18N = True          # Enable internationalization
USE_L10N = True          # Enable localization
USE_TZ = True            # Enable timezone support

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', '简体中文'),
    ('zh-hant', '繁體中文'),
    ('ja', '日本語'),
    ('ko', '한국어'),
    ('es', 'Español'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
    ('pt', 'Português'),
    ('ru', 'Русский'),
]

# Locale paths for translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
if os.environ.get('DISABLE_MANIFEST_STATIC'):
    # For test environment to avoid errors when admin static not collected
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============== REST FRAMEWORK CONFIGURATION ==============

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ============== JWT CONFIGURATION ==============

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# ============== CORS CONFIGURATION ==============

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

CORS_ALLOW_CREDENTIALS = True

# ============== SPECTACULAR CONFIGURATION ==============

SPECTACULAR_SETTINGS = {
    'TITLE': 'TubeWhale API',
    'DESCRIPTION': 'YouTube视频分析平台API文档',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
}

# ============== REDIS CONFIGURATION ==============

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    },
    # Redis配置（需要Redis服务器）
    # 'default': {
    #     'BACKEND': 'django_redis.cache.RedisCache',
    #     'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
    #     'OPTIONS': {
    #         'CLIENT_CLASS': 'django_redis.client.DefaultClient',
    #     }
    # }
}

# ============== CELERY CONFIGURATION ==============

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# ============== LOGGING CONFIGURATION ==============

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# ============== GUARDIAN CONFIGURATION ==============

ANONYMOUS_USER_NAME = None
GUARDIAN_RAISE_403 = True

# ============== TEMPLATE ENGINE / PUBLIC PREVIEW FLAGS ==============
# 控制是否允许未认证用户通过 /templates-public/ 访问模板列表和只读预览。
# 生产环境可设为 False 关闭。
PUBLIC_TEMPLATE_PREVIEW_ENABLED = os.environ.get('PUBLIC_TEMPLATE_PREVIEW_ENABLED', 'true').lower() == 'true'

# 是否在简单仪表板中显示企业引擎实际模板列表（若引擎加载失败则自动降级为空列表）
ENTERPRISE_TEMPLATE_DASHBOARD_ENABLED = os.environ.get('ENTERPRISE_TEMPLATE_DASHBOARD_ENABLED', 'true').lower() == 'true'

# CLI execution persistence & export safeguards
CLI_PERSIST_ENABLED = os.environ.get('CLI_PERSIST_ENABLED', 'true').lower() == 'true'
# Hard cap for export & graph endpoints to prevent accidental massive dumps
MAX_CLI_EXPORT_LIMIT = int(os.environ.get('MAX_CLI_EXPORT_LIMIT', '5000'))

# ============== SYSTEM METRICS THRESHOLDS ==============
# Warn / critical thresholds for CPU & memory; used by admin metrics dashboard & hotspot events.
CPU_WARN_THRESHOLD = float(os.environ.get('CPU_WARN_THRESHOLD', '70'))  # percent
CPU_CRIT_THRESHOLD = float(os.environ.get('CPU_CRIT_THRESHOLD', '90'))
MEM_WARN_THRESHOLD = float(os.environ.get('MEM_WARN_THRESHOLD', '75'))
MEM_CRIT_THRESHOLD = float(os.environ.get('MEM_CRIT_THRESHOLD', '90'))
HOTSPOT_MIN_DURATION_SEC = int(os.environ.get('HOTSPOT_MIN_DURATION_SEC', '30'))  # consecutive seconds beyond crit to log event

# ============== DJANGO CHANNELS & WEBSOCKET CONFIGURATION ==============
# 🎯 ASGI Application for WebSocket support
ASGI_APPLICATION = 'tubewhale_project.asgi.application'

# 🎯 Channel Layers - Redis backend for real-time communication
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')],
            "capacity": 1500,  # 🔥 High capacity for industrial-grade performance
            "expiry": 60,      # 🔥 Message expiry time in seconds
        },
    },
}

# 🎯 WebSocket Authentication
CHANNEL_ROUTING = {
    # WebSocket routing will be handled in routing.py
}

# 🎯 Real-time Video Processing Configuration
VIDEO_PROCESSING_CONFIG = {
    'MAX_CONCURRENT_VIDEOS': int(os.environ.get('MAX_CONCURRENT_VIDEOS', '5')),
    'STATUS_UPDATE_INTERVAL': float(os.environ.get('STATUS_UPDATE_INTERVAL', '0.5')),  # seconds
    'WEBSOCKET_HEARTBEAT_INTERVAL': int(os.environ.get('WEBSOCKET_HEARTBEAT_INTERVAL', '30')),  # seconds
    'DATABASE_MONITOR_INTERVAL': float(os.environ.get('DATABASE_MONITOR_INTERVAL', '1.0')),  # seconds
}
