# Generated by Django 4.2.7 on 2025-09-22 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tubewhale_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CLICommandLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("command", models.CharField(db_index=True, max_length=100)),
                ("args", models.JSONField(blank=True, default=list)),
                ("return_code", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("stdout_truncated", models.TextField(blank=True)),
                ("stderr_truncated", models.TextField(blank=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "rate_bucket",
                    models.CharField(
                        blank=True, help_text="Rate limiting bucket key", max_length=64
                    ),
                ),
                ("error_flag", models.BooleanField(default=False)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "CLI Command Log",
                "verbose_name_plural": "CLI Command Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="processingjob",
            new_name="tubewhale_e_user_id_235fcd_idx",
            old_name="tubewhale_e_user_id_0a9f5d_idx",
        ),
        migrations.RenameIndex(
            model_name="processingjob",
            new_name="tubewhale_e_video_i_70c0ef_idx",
            old_name="tubewhale_e_video_i_9a89d6_idx",
        ),
        migrations.RenameIndex(
            model_name="processingjob",
            new_name="tubewhale_e_created_be3460_idx",
            old_name="tubewhale_e_created_339e1e_idx",
        ),
        migrations.RenameIndex(
            model_name="videoprocessingresult",
            new_name="tubewhale_e_video_i_362788_idx",
            old_name="tubewhale_e_video_i_81a9d2_idx",
        ),
        migrations.RenameIndex(
            model_name="videoprocessingresult",
            new_name="tubewhale_e_created_e50502_idx",
            old_name="tubewhale_e_created_3bcb0f_idx",
        ),
        migrations.AlterField(
            model_name="tubewhaleengineconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="videoprocessingresult",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="clicommandlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cli_command_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="clicommandlog",
            index=models.Index(
                fields=["command", "created_at"], name="tubewhale_e_command_2dfd3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clicommandlog",
            index=models.Index(
                fields=["user", "created_at"], name="tubewhale_e_user_id_1eed53_idx"
            ),
        ),
    ]
