# Generated by Django 4.2.7 on 2025-09-24 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tubewhale_engine', '0002_clicommandlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('job_id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('analysis_type', models.CharField(choices=[('video', 'Video Analysis'), ('playlist', 'Playlist Analysis'), ('batch', 'Batch Analysis'), ('custom', 'Custom Analysis')], default='video', max_length=20)),
                ('expert_role', models.CharField(max_length=50)),
                ('template_id', models.CharField(max_length=50)),
                ('content_id', models.CharField(max_length=100)),
                ('content_url', models.URLField(blank=True, max_length=500)),
                ('content_title', models.TextField(blank=True)),
                ('content_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('custom_questions', models.JSONField(blank=True, default=list)),
                ('analysis_options', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('api_version', models.CharField(default='v1', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tubewhale_analysis_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(default=dict, help_text='Raw analysis data')),
                ('insights', models.JSONField(default=dict, help_text='Processed insights and recommendations')),
                ('metrics', models.JSONField(default=dict, help_text='Performance metrics and scores')),
                ('summary', models.TextField(blank=True, help_text='Executive summary')),
                ('detailed_analysis', models.TextField(blank=True, help_text='Detailed analysis content')),
                ('recommendations', models.TextField(blank=True, help_text='Actionable recommendations')),
                ('charts_data', models.JSONField(blank=True, default=dict, help_text='Chart and visualization data')),
                ('screenshots', models.JSONField(blank=True, default=list, help_text='Screenshot URLs')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Analysis confidence (0-1)')),
                ('completeness_score', models.FloatField(default=0.0, help_text='Data completeness (0-1)')),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('available_formats', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tubewhale_engine.analysisjob')),
            ],
            options={
                'db_table': 'tubewhale_analysis_results',
            },
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', 'created_at'], name='tubewhale_a_status_5f9fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['analysis_type', 'expert_role'], name='tubewhale_a_analysi_c0c670_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['content_id'], name='tubewhale_a_content_b04e5d_idx'),
        ),
    ]
