# Generated by Django 4.2.7 on 2025-09-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubewhale_engine', '0003_analysisjob_analysisresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='status_message',
            field=models.CharField(blank=True, help_text='Current status message', max_length=200),
        ),
    ]
