# Generated by Django 4.2.7 on 2025-09-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubewhale_engine', '0004_analysisjob_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Celery task ID for async processing', max_length=128),
        ),
    ]
