# Generated by Django 4.2.7 on 2025-09-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubewhale_engine', '0005_add_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='current_step',
            field=models.CharField(blank=True, help_text='Current processing step', max_length=100),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='estimated_time_remaining',
            field=models.IntegerField(blank=True, help_text='Estimated seconds remaining', null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='steps_completed',
            field=models.IntegerField(default=0, help_text='Number of completed steps'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='total_steps',
            field=models.IntegerField(default=5, help_text='Total number of steps'),
        ),
    ]
