# Generated by Django 4.2.7 on 2025-09-26 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tubewhale_engine', '0006_analysisjob_current_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField(help_text='CPU使用百分比')),
                ('memory_percent', models.FloatField(help_text='内存使用百分比')),
                ('disk_io_read_mb', models.FloatField(default=0, help_text='磁盘读取量(MB)')),
                ('disk_io_write_mb', models.FloatField(default=0, help_text='磁盘写入量(MB)')),
                ('network_sent_kb', models.FloatField(default=0, help_text='网络发送量(KB)')),
                ('network_recv_kb', models.FloatField(default=0, help_text='网络接收量(KB)')),
                ('api_response_time_ms', models.IntegerField(blank=True, help_text='API响应时间(毫秒)', null=True)),
                ('queue_wait_time_ms', models.IntegerField(blank=True, help_text='队列等待时间(毫秒)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='tubewhale_engine.analysisjob')),
            ],
            options={
                'db_table': 'tubewhale_performance_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(help_text='执行步骤名称', max_length=200)),
                ('details', models.JSONField(default=dict, help_text='详细执行信息')),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='执行时间(毫秒)', null=True)),
                ('cpu_usage_percent', models.FloatField(blank=True, help_text='CPU使用率', null=True)),
                ('memory_usage_mb', models.FloatField(blank=True, help_text='内存使用量(MB)', null=True)),
                ('api_calls_count', models.IntegerField(default=0, help_text='API调用次数')),
                ('data_processed_kb', models.IntegerField(blank=True, help_text='处理的数据量(KB)', null=True)),
                ('warnings', models.JSONField(blank=True, default=list, help_text='警告信息')),
                ('errors', models.JSONField(blank=True, default=list, help_text='错误信息')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='tubewhale_engine.analysisjob')),
            ],
            options={
                'db_table': 'tubewhale_execution_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['job', 'timestamp'], name='tubewhale_e_job_id_0588b9_idx'), models.Index(fields=['step_name', 'timestamp'], name='tubewhale_e_step_na_f43cec_idx')],
            },
        ),
    ]
