# Generated by Django 4.2.7 on 2025-09-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='Icon Class')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color Code')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Category',
                'verbose_name_plural': 'Template Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('full_description', models.TextField(verbose_name='Full Description')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, verbose_name='Tags')),
                ('required_tier', models.CharField(choices=[('basic', 'Basic - Available to all users'), ('standard', 'Standard - Requires Standard+ tier'), ('premium', 'Premium - Requires Premium tier')], default='basic', max_length=20, verbose_name='Required Tier')),
                ('complexity_level', models.CharField(choices=[('beginner', 'Beginner - Simple analysis'), ('intermediate', 'Intermediate - Moderate complexity'), ('advanced', 'Advanced - Complex analysis'), ('expert', 'Expert - Highly specialized')], default='beginner', max_length=20, verbose_name='Complexity Level')),
                ('icon', models.CharField(default='fas fa-chart-bar', max_length=50, verbose_name='Icon Class')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color Code')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/', verbose_name='Preview Image')),
                ('estimated_duration', models.CharField(blank=True, max_length=100, verbose_name='Estimated Duration')),
                ('output_formats', models.CharField(blank=True, help_text='e.g., PDF, CSV, JSON', max_length=200, verbose_name='Output Formats')),
                ('sample_use_cases', models.TextField(blank=True, verbose_name='Sample Use Cases')),
                ('template_id', models.CharField(max_length=100, unique=True, verbose_name='Internal Template ID')),
                ('parameters_schema', models.JSONField(blank=True, default=dict, verbose_name='Parameters Schema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Usage Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='dashboard_app.templatecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Analysis Template',
                'verbose_name_plural': 'Analysis Templates',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
    ]
