# Generated by Django 4.2.7 on 2025-09-16 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='领域名称', max_length=100, unique=True)),
                ('code', models.CharField(help_text='领域代码', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='领域描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('prompt_template', models.TextField(blank=True, help_text='提示词模板')),
                ('analysis_keywords', models.JSONField(default=list, help_text='分析关键词列表')),
                ('priority', models.IntegerField(default=0, help_text='优先级(数值越大优先级越高)')),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='置信度阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '专家领域',
                'verbose_name_plural': '专家领域管理',
                'db_table': 'expert_domains',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='报告标题', max_length=500)),
                ('report_type', models.CharField(choices=[('transcript', '转录报告'), ('audio', '音频分析报告'), ('search', '搜索分析报告'), ('summary', '总结报告'), ('comprehensive', '综合分析报告')], help_text='报告类型', max_length=20)),
                ('executive_summary', models.TextField(help_text='执行摘要')),
                ('content', models.TextField(help_text='报告正文')),
                ('conclusions', models.TextField(blank=True, help_text='结论')),
                ('recommendations', models.TextField(blank=True, help_text='建议')),
                ('word_count', models.IntegerField(default=0, help_text='字数统计')),
                ('reading_time', models.IntegerField(default=0, help_text='预计阅读时间(分钟)')),
                ('tags', models.JSONField(default=list, help_text='标签列表')),
                ('confidence_score', models.FloatField(default=0.0, help_text='整体置信度(0-1)')),
                ('quality_score', models.FloatField(default=0.0, help_text='质量评分(0-1)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('processing', '处理中'), ('completed', '已完成'), ('reviewed', '已审核'), ('published', '已发布')], default='draft', help_text='报告状态', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('analysis_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='video_app.analysistask', verbose_name='分析任务')),
                ('expert_domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis_app.expertdomain', verbose_name='专家领域')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to='video_app.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告管理',
                'db_table': 'analysis_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('accuracy', '准确度'), ('relevance', '相关性'), ('completeness', '完整性'), ('clarity', '清晰度'), ('objectivity', '客观性'), ('depth', '深度'), ('insight', '洞察力')], help_text='指标类型', max_length=20)),
                ('name', models.CharField(help_text='指标名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='指标描述')),
                ('value', models.FloatField(help_text='指标值')),
                ('min_value', models.FloatField(default=0.0, help_text='最小值')),
                ('max_value', models.FloatField(default=1.0, help_text='最大值')),
                ('unit', models.CharField(blank=True, help_text='单位', max_length=20)),
                ('calculation_method', models.CharField(blank=True, help_text='计算方法', max_length=100)),
                ('data_source', models.CharField(blank=True, help_text='数据来源', max_length=100)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='测量时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analysis_app.analysisreport', verbose_name='分析报告')),
            ],
            options={
                'verbose_name': '分析指标',
                'verbose_name_plural': '分析指标管理',
                'db_table': 'analysis_metrics',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='洞察标题', max_length=200)),
                ('description', models.TextField(help_text='洞察描述')),
                ('insight_type', models.CharField(choices=[('trend', '趋势'), ('pattern', '模式'), ('anomaly', '异常'), ('correlation', '关联'), ('prediction', '预测'), ('recommendation', '建议')], help_text='洞察类型', max_length=20)),
                ('importance', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '关键')], default='medium', help_text='重要性', max_length=20)),
                ('supporting_data', models.JSONField(default=dict, help_text='支撑数据')),
                ('confidence_level', models.FloatField(default=0.5, help_text='置信水平(0-1)')),
                ('evidence_count', models.IntegerField(default=0, help_text='证据数量')),
                ('tags', models.JSONField(default=list, help_text='标签列表')),
                ('category', models.CharField(blank=True, help_text='分类', max_length=100)),
                ('actionable', models.BooleanField(default=False, help_text='是否可执行')),
                ('action_items', models.TextField(blank=True, help_text='行动项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='analysis_app.analysisreport', verbose_name='分析报告')),
            ],
            options={
                'verbose_name': '分析洞察',
                'verbose_name_plural': '分析洞察管理',
                'db_table': 'analysis_insights',
                'ordering': ['-importance', '-confidence_level', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisreport',
            index=models.Index(fields=['video', '-created_at'], name='analysis_re_video_i_fe8e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisreport',
            index=models.Index(fields=['user', '-created_at'], name='analysis_re_user_id_8cad3b_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisreport',
            index=models.Index(fields=['report_type'], name='analysis_re_report__64fab0_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisreport',
            index=models.Index(fields=['status'], name='analysis_re_status_188fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='analysismetrics',
            index=models.Index(fields=['report', 'metric_type'], name='analysis_me_report__f6f4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='analysismetrics',
            index=models.Index(fields=['metric_type', 'value'], name='analysis_me_metric__45346f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analysismetrics',
            unique_together={('report', 'metric_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='analysisinsight',
            index=models.Index(fields=['report', '-importance'], name='analysis_in_report__942991_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisinsight',
            index=models.Index(fields=['insight_type', '-confidence_level'], name='analysis_in_insight_03b674_idx'),
        ),
    ]
