# Generated by Django 4.2.7 on 2025-09-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisinsight',
            options={'ordering': ['-importance', '-confidence_level', '-created_at'], 'verbose_name': 'Analysis Insight', 'verbose_name_plural': 'Analysis Insight Management'},
        ),
        migrations.AlterModelOptions(
            name='analysismetrics',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Analysis Metric', 'verbose_name_plural': 'Analysis Metric Management'},
        ),
        migrations.AlterModelOptions(
            name='analysisreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analysis Report', 'verbose_name_plural': 'Analysis Report Management'},
        ),
        migrations.AlterModelOptions(
            name='expertdomain',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Expert Domain', 'verbose_name_plural': 'Expert Domain Management'},
        ),
    ]
