# Generated by Django 4.2.7 on 2025-09-16 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_id', models.CharField(help_text='YouTube视频ID', max_length=50, unique=True)),
                ('title', models.CharField(help_text='视频标题', max_length=500)),
                ('description', models.TextField(blank=True, help_text='视频描述')),
                ('url', models.URLField(help_text='YouTube视频URL')),
                ('duration', models.IntegerField(blank=True, help_text='视频时长(秒)', null=True)),
                ('view_count', models.BigIntegerField(blank=True, help_text='观看次数', null=True)),
                ('like_count', models.BigIntegerField(blank=True, help_text='点赞数', null=True)),
                ('comment_count', models.BigIntegerField(blank=True, help_text='评论数', null=True)),
                ('publish_date', models.DateTimeField(blank=True, help_text='发布时间', null=True)),
                ('channel_name', models.CharField(blank=True, help_text='频道名称', max_length=200)),
                ('channel_id', models.CharField(blank=True, help_text='频道ID', max_length=100)),
                ('local_file_path', models.CharField(blank=True, help_text='本地文件路径', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='文件大小(字节)', null=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('downloading', '下载中'), ('downloaded', '下载完成'), ('analyzing', '分析中'), ('completed', '已完成'), ('failed', '失败')], default='pending', help_text='处理状态', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='下载时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频管理',
                'db_table': 'videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('transcript', '转录分析'), ('audio', '音频分析'), ('search', '搜索分析'), ('summarize', '总结分析'), ('comprehensive', '综合分析')], help_text='分析类型', max_length=20)),
                ('expert_domain', models.CharField(choices=[('general', '通用'), ('technology', '科技'), ('business', '商业'), ('education', '教育'), ('entertainment', '娱乐'), ('news', '新闻'), ('health', '健康'), ('finance', '金融')], default='general', help_text='专家领域', max_length=20)),
                ('analysis_depth', models.IntegerField(default=3, help_text='分析深度(1-5)')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', help_text='任务状态', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='进度百分比')),
                ('error_message', models.TextField(blank=True, help_text='错误信息')),
                ('result_data', models.JSONField(blank=True, help_text='分析结果数据', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='置信度分数', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery任务ID', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to='video_app.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '分析任务',
                'verbose_name_plural': '分析任务管理',
                'db_table': 'analysis_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='标签名称', max_length=100)),
                ('tag_type', models.CharField(choices=[('category', '分类'), ('topic', '主题'), ('keyword', '关键词'), ('emotion', '情感'), ('quality', '质量')], help_text='标签类型', max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='置信度(0-1)')),
                ('source', models.CharField(default='auto', help_text='标签来源(auto/manual)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='video_app.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频标签',
                'verbose_name_plural': '视频标签管理',
                'db_table': 'video_tags',
                'indexes': [models.Index(fields=['video'], name='video_tags_video_i_4fc13d_idx'), models.Index(fields=['name'], name='video_tags_name_e75087_idx'), models.Index(fields=['tag_type'], name='video_tags_tag_typ_85c588_idx')],
                'unique_together': {('video', 'name', 'tag_type')},
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_comment_id', models.CharField(help_text='YouTube评论ID', max_length=100, unique=True)),
                ('author', models.CharField(help_text='评论作者', max_length=200)),
                ('text', models.TextField(help_text='评论内容')),
                ('like_count', models.IntegerField(default=0, help_text='点赞数')),
                ('reply_count', models.IntegerField(default=0, help_text='回复数')),
                ('published_at', models.DateTimeField(help_text='发布时间')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='收集时间')),
                ('sentiment_score', models.FloatField(blank=True, help_text='情感分数(-1到1)', null=True)),
                ('is_spam', models.BooleanField(default=False, help_text='是否为垃圾评论')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video_app.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频评论',
                'verbose_name_plural': '视频评论管理',
                'db_table': 'video_comments',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['video', '-published_at'], name='video_comme_video_i_a35b29_idx'), models.Index(fields=['youtube_comment_id'], name='video_comme_youtube_8e979e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['youtube_id'], name='videos_youtube_32ded2_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user', '-created_at'], name='videos_user_id_5f9058_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='videos_status_510af8_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['video', '-created_at'], name='analysis_ta_video_i_c2af98_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['user', '-created_at'], name='analysis_ta_user_id_5fff94_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['status'], name='analysis_ta_status_a9aced_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['celery_task_id'], name='analysis_ta_celery__35c9ca_idx'),
        ),
    ]
