# Generated by Django 4.2.7 on 2025-09-26 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysistask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analysis Task', 'verbose_name_plural': 'Analysis Task Management'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Video Management'},
        ),
        migrations.AlterModelOptions(
            name='videocomment',
            options={'ordering': ['-published_at'], 'verbose_name': 'Video Comment', 'verbose_name_plural': 'Video Comment Management'},
        ),
        migrations.AlterModelOptions(
            name='videotag',
            options={'verbose_name': 'Video Tag', 'verbose_name_plural': 'Video Tag Management'},
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='处理状态', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
