# Generated by hand

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0008_systemhotspotevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(help_text='Unique identifier for the template', max_length=100, unique=True, verbose_name='Template ID')),
                ('title', models.CharField(help_text='Display name for the template', max_length=200, verbose_name='Template Title')),
                ('description', models.TextField(help_text='Detailed description of what this template does', verbose_name='Description')),
                ('theme', models.CharField(help_text='Main theme or topic area', max_length=100, verbose_name='Theme')),
                ('category', models.CharField(choices=[('research', 'Research & Analysis'), ('content', 'Content Creation'), ('automation', 'Automation & Workflows'), ('visualization', 'Data Visualization'), ('reporting', 'Reporting & Insights'), ('integration', 'System Integration'), ('custom', 'Custom Solutions')], default='research', help_text='Template category for organization', max_length=50, verbose_name='Category')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text='Required skill level', max_length=20, verbose_name='Difficulty Level')),
                ('estimated_time', models.CharField(help_text='Estimated time to complete (e.g., "15-30 minutes")', max_length=50, verbose_name='Estimated Time')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of key features and capabilities', verbose_name='Features')),
                ('use_cases', models.JSONField(blank=True, default=list, help_text='Common use cases and scenarios', verbose_name='Use Cases')),
                ('required_tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', help_text='Minimum subscription tier required', max_length=20, verbose_name='Required Tier')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for selection', verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for display in lists (lower numbers first)', verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Template Information',
                'verbose_name_plural': 'Template Information',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]