# Generated by Django 4.2.7 on 2025-09-26 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates_app', '0009_templateinfo'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "templates_c_command_a74b23_idx" RENAME TO "templates_c_command_37f35f_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "templates_c_command_37f35f_idx" RENAME TO "templates_c_command_a74b23_idx";',
            state_operations=[
                migrations.RenameIndex(
                    model_name='cliexecution',
                    new_name='templates_c_command_37f35f_idx',
                    old_name='templates_c_command_a74b23_idx',
                )
            ],
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "templates_c_status_caeaf2_idx" RENAME TO "templates_c_status_89bad2_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "templates_c_status_89bad2_idx" RENAME TO "templates_c_status_caeaf2_idx";',
            state_operations=[
                migrations.RenameIndex(
                    model_name='cliexecution',
                    new_name='templates_c_status_89bad2_idx',
                    old_name='templates_c_status_caeaf2_idx',
                )
            ],
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "templates_c_template_05b40e_idx" RENAME TO "templates_c_templat_1f82c1_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "templates_c_templat_1f82c1_idx" RENAME TO "templates_c_template_05b40e_idx";',
            state_operations=[
                migrations.RenameIndex(
                    model_name='cliexecution',
                    new_name='templates_c_templat_1f82c1_idx',
                    old_name='templates_c_template_05b40e_idx',
                )
            ],
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "templates_a_role_do_5f25cc_idx" RENAME TO "templates_e_role_514520_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "templates_e_role_514520_idx" RENAME TO "templates_a_role_do_5f25cc_idx";',
            state_operations=[
                migrations.RenameIndex(
                    model_name='expertprompt',
                    new_name='templates_e_role_514520_idx',
                    old_name='templates_a_role_do_5f25cc_idx',
                )
            ],
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "job_status_created_idx" RENAME TO "templates_j_status_fe0e0b_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "templates_j_status_fe0e0b_idx" RENAME TO "job_status_created_idx";',
            state_operations=[
                migrations.RenameIndex(
                    model_name='job',
                    new_name='templates_j_status_fe0e0b_idx',
                    old_name='job_status_created_idx',
                )
            ],
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "templates__user_id_9f4f2c_idx" RENAME TO "templates_u_user_id_751324_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "templates_u_user_id_751324_idx" RENAME TO "templates__user_id_9f4f2c_idx";',
            state_operations=[
                migrations.RenameIndex(
                    model_name='usertemplateselection',
                    new_name='templates_u_user_id_751324_idx',
                    old_name='templates__user_id_9f4f2c_idx',
                )
            ],
        ),
        migrations.AlterField(
            model_name='expertprompt',
            name='prompt_intro',
            field=models.TextField(blank=True, default='', help_text='Optional preface injected before base template prompt'),
        ),
        migrations.AlterField(
            model_name='expertprompt',
            name='prompt_outro',
            field=models.TextField(blank=True, default='', help_text='Optional suffix appended after base template prompt'),
        ),
        migrations.AlterField(
            model_name='expertprompt',
            name='weight',
            field=models.PositiveIntegerField(default=100, help_text='Ordering / priority (lower = earlier)'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='category',
            field=models.CharField(choices=[('research', 'Research & Analysis'), ('content', 'Content Creation'), ('business', 'Business Intelligence'), ('education', 'Educational'), ('technical', 'Technical Analysis'), ('social', 'Social Media Analysis')], default='research', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner - Easy to use'), ('intermediate', 'Intermediate - Some experience needed'), ('advanced', 'Advanced - Expert users')], default='beginner', max_length=20, verbose_name='Difficulty Level'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='estimated_time',
            field=models.CharField(help_text="e.g., '5-10 minutes', '30+ minutes'", max_length=50, verbose_name='Estimated Processing Time'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='features',
            field=models.JSONField(default=list, help_text='List of key features or capabilities', verbose_name='Key Features'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='required_tier',
            field=models.CharField(choices=[('basic', 'Basic Tier'), ('standard', 'Standard Tier'), ('premium', 'Premium Tier')], default='basic', max_length=20, verbose_name='Required Tier'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='template_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Template ID'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='theme',
            field=models.CharField(help_text="Main theme or topic (e.g., 'Business Analysis', 'Content Research')", max_length=100, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Template Title'),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='templateinfo',
            name='use_cases',
            field=models.JSONField(default=list, help_text='List of common use cases or scenarios', verbose_name='Use Cases'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
