# Generated by Django 4.2.7 on 2025-09-16 05:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, help_text='用户手机号', max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='用户头像', null=True, upload_to='avatars/')),
                ('timezone_setting', models.CharField(default='UTC', help_text='用户时区', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', '中文'), ('es', 'Español'), ('fr', 'Français')], default='en', help_text='界面语言', max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text='邮箱是否已验证')),
                ('api_calls_today', models.IntegerField(default=0, help_text='今日API调用次数')),
                ('total_api_calls', models.IntegerField(default=0, help_text='总API调用次数')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='最后活动时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='tubewhale_user_set', related_query_name='tubewhale_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='tubewhale_user_set', related_query_name='tubewhale_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='API Key名称', max_length=100)),
                ('key', models.CharField(help_text='API密钥', max_length=64, unique=True)),
                ('prefix', models.CharField(help_text='密钥前缀', max_length=8)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('rate_limit', models.IntegerField(default=1000, help_text='每日调用限制')),
                ('allowed_ips', models.TextField(blank=True, help_text='允许的IP地址列表，用逗号分隔')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('usage_count', models.IntegerField(default=0, help_text='使用次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥管理',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(help_text='API端点', max_length=200)),
                ('method', models.CharField(help_text='HTTP方法', max_length=10)),
                ('ip_address', models.GenericIPAddressField(help_text='客户端IP')),
                ('user_agent', models.TextField(blank=True, help_text='用户代理')),
                ('status_code', models.IntegerField(help_text='HTTP状态码')),
                ('response_time', models.FloatField(help_text='响应时间(秒)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='user_app.apikey', verbose_name='API密钥')),
            ],
            options={
                'verbose_name': 'API使用日志',
                'verbose_name_plural': 'API使用日志',
                'db_table': 'api_usage_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_key', '-timestamp'], name='api_usage_l_api_key_aef8f3_idx'), models.Index(fields=['timestamp'], name='api_usage_l_timesta_5a0769_idx')],
            },
        ),
    ]
