# Generated by Django 4.2.7 on 2025-09-16 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Key Management'},
        ),
        migrations.AlterModelOptions(
            name='apiusagelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'API Usage Log', 'verbose_name_plural': 'API Usage Logs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User Management'},
        ),
        migrations.AlterField(
            model_name='apikey',
            name='allowed_ips',
            field=models.TextField(blank=True, help_text='Allowed IP addresses, comma separated', verbose_name='Allowed IPs'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the key is active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(help_text='API key string', max_length=64, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Used'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(help_text='API Key name', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(help_text='Key prefix', max_length=8, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='rate_limit',
            field=models.IntegerField(default=1000, help_text='Daily call limit', verbose_name='Rate Limit'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Number of times used', verbose_name='Usage Count'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='user_app.apikey', verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='endpoint',
            field=models.CharField(help_text='API endpoint', max_length=200, verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Client IP address', verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='method',
            field=models.CharField(help_text='HTTP method', max_length=10, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='response_time',
            field=models.FloatField(help_text='Response time in seconds', verbose_name='Response Time'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='status_code',
            field=models.IntegerField(help_text='HTTP status code', verbose_name='Status Code'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string', verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_calls_today',
            field=models.IntegerField(default=0, help_text="Today's API call count", verbose_name='API Calls Today'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User avatar image', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='tubewhale_user_set', related_query_name='tubewhale_user', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email verification status', verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', '简体中文'), ('zh-hant', '繁體中文'), ('ja', '日本語'), ('ko', '한국어'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('pt', 'Português'), ('ru', 'Русский')], default='en', help_text='User interface language', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='Last activity timestamp', verbose_name='Last Activity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='User phone number', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone_setting',
            field=models.CharField(default='UTC', help_text='User timezone setting', max_length=50, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_api_calls',
            field=models.IntegerField(default=0, help_text='Total API call count', verbose_name='Total API Calls'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='tubewhale_user_set', related_query_name='tubewhale_user', to='auth.permission', verbose_name='User Permissions'),
        ),
    ]
