# Generated by Django 4.2.7 on 2025-09-16 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_apikey_options_alter_apiusagelog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique invitation code', max_length=20, unique=True, verbose_name='Invitation Code')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this code has been used', verbose_name='Used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this code was used', null=True, verbose_name='Used At')),
                ('expires_at', models.DateTimeField(help_text='When this code expires', verbose_name='Expires At')),
                ('max_uses', models.IntegerField(default=1, help_text='Maximum number of times this code can be used', verbose_name='Max Uses')),
                ('current_uses', models.IntegerField(default=0, help_text='Number of times this code has been used', verbose_name='Current Uses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this invitation code', verbose_name='Notes')),
                ('allowed_domains', models.TextField(blank=True, help_text='Comma-separated list of allowed email domains', verbose_name='Allowed Domains')),
                ('created_by', models.ForeignKey(help_text='Admin who created this code', on_delete=django.db.models.deletion.CASCADE, related_name='created_invitation_codes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('used_by', models.ForeignKey(blank=True, help_text='User who used this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitation_codes', to=settings.AUTH_USER_MODEL, verbose_name='Used By')),
            ],
            options={
                'verbose_name': 'Invitation Code',
                'verbose_name_plural': 'Invitation Codes',
                'db_table': 'invitation_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='invitation__code_b5d026_idx'), models.Index(fields=['is_used', 'expires_at'], name='invitation__is_used_5573dd_idx'), models.Index(fields=['created_at'], name='invitation__created_ac52d1_idx')],
            },
        ),
    ]
