# Generated by Django 4.2.7 on 2025-09-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_invitationcode'),
    ]

    operations = [
    ]
