# Generated by Django 4.2.7 on 2025-09-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0004_auto_20250916_0733"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tier",
            field=models.CharField(
                choices=[
                    ("basic", "Basic Tier - Default templates only"),
                    ("standard", "Standard Tier - Template switching"),
                    ("premium", "Premium Tier - Custom AI interactions"),
                ],
                default="basic",
                help_text="Determines template access level",
                max_length=20,
                verbose_name="User Tier",
            ),
        ),
    ]
