# Generated by Django 4.2.7 on 2025-09-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0005_user_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="key_type",
            field=models.CharField(
                choices=[
                    ("user_generated", "User Generated"),
                    ("admin_configured", "Admin Configured"),
                    ("system_default", "System Default"),
                ],
                default="user_generated",
                help_text="How this API key was created",
                max_length=20,
                verbose_name="Key Type",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI API"),
                    ("youtube", "YouTube API"),
                    ("other", "Other Service"),
                ],
                default="other",
                help_text="Type of service this API key is for",
                max_length=20,
                verbose_name="Service Type",
            ),
        ),
    ]
