# Generated by Django 4.2.7 on 2025-09-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0006_apikey_key_type_apikey_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="original_key_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash of original admin key for reference",
                max_length=64,
                null=True,
                verbose_name="Original Key Hash",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(
                help_text="API key string", max_length=128, verbose_name="Key"
            ),
        ),
    ]
