# Generated by Django 4.2.7 on 2025-09-24 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0007_apikey_original_key_hash_alter_apikey_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnalysisHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scenario_type",
                    models.CharField(max_length=50, verbose_name="Analysis Scenario"),
                ),
                ("youtube_url", models.URLField(verbose_name="YouTube URL")),
                (
                    "video_title",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis_result",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Analysis Result"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("tokens_used", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Analysis History",
                "verbose_name_plural": "User Analysis Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="user_app_us_user_id_996cd2_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="user_app_us_status_3d060f_idx",
                    ),
                ],
            },
        ),
    ]
