# Generated by Django 4.2.7 on 2025-09-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_useranalysishistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic Tier - Default templates only'), ('standard', 'Standard Tier - Template switching'), ('premium', 'Premium Tier - Custom AI interactions'), ('enterprise', 'Enterprise Tier - Full system access')], default='basic', help_text='Determines template access level', max_length=20, verbose_name='User Tier'),
        ),
    ]
