# Generated by Django 4.2.7 on 2025-09-26 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_user_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ja', 'Japanese'), ('ko', '한국어'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('pt', 'Português'), ('ru', 'Русский')], default='en', help_text='User interface language', max_length=10, verbose_name='Language'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_keys', models.JSONField(blank=True, default=dict, help_text='User API keys storage')),
                ('workspace_folder', models.CharField(blank=True, max_length=500, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('preferred_template', models.CharField(default='default_analysis', max_length=100)),
                ('subscription_tier', models.CharField(default='basic', max_length=50)),
                ('auto_analysis', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
